<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_AltaShop_v-icon notranslate fas fa-user t_f0827e</name>
   <tag></tag>
   <elementGuidId>07628afd-b129-472a-8e44-25e6420cdd50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.v-icon.notranslate.fas.fa-user.theme--dark</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/header/div/button[2]/span/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>0ba9ea34-c284-4f90-8e50-00839a3a0376</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>432bb84a-8f2b-484d-ab77-c1a69fa1a213</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-icon notranslate fas fa-user theme--dark</value>
      <webElementGuid>6fb263f9-c5ee-4710-866a-3549c15a4ffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/header[@class=&quot;v-sheet theme--dark v-toolbar v-app-bar v-app-bar--fixed deep-purple accent-4&quot;]/div[@class=&quot;v-toolbar__content&quot;]/button[@class=&quot;v-btn v-btn--icon v-btn--round theme--dark v-size--default&quot;]/span[@class=&quot;v-btn__content&quot;]/i[@class=&quot;v-icon notranslate fas fa-user theme--dark&quot;]</value>
      <webElementGuid>5868164a-c094-4880-87b1-6ccebe045a0a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/header/div/button[2]/span/i</value>
      <webElementGuid>3d46e697-12bb-4bd3-8e57-767a2dafda46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span/i</value>
      <webElementGuid>c5bb0962-0032-4fb1-8894-5a94588c5d83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
