<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_input-18</name>
   <tag></tag>
   <elementGuidId>2b2b25bf-d0f5-42eb-ac28-9a2ae5d27247</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-18</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-18']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1c934252-bcfd-4073-8a6a-ca00646d18bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-18</value>
      <webElementGuid>dcaba09f-bb2d-49ae-ac19-5beb7da4a26f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5ff320ad-52ee-4c2c-87b6-e48918b82065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-18&quot;)</value>
      <webElementGuid>6b42a2fd-56ee-4cf7-9717-02911111828c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-18']</value>
      <webElementGuid>f95e0023-d000-4a2f-9c2f-00b562ced8b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/main/div/div/div/div[2]/form/div/div/div/div/input</value>
      <webElementGuid>665ef522-b365-4010-b53f-996e5871f223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>cf5353a1-7bfb-4444-b3e7-dd8d6cd61507</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-18' and @type = 'text']</value>
      <webElementGuid>d6cd1c2c-53b1-4c31-ad82-bb3b0fc10861</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
