<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_AltaShop0</name>
   <tag></tag>
   <elementGuidId>0f5e53ad-658a-412b-ad46-685de3f58610</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.v-toolbar__content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/header/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>564d4758-6734-47e2-9ea0-3eca07139642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-toolbar__content</value>
      <webElementGuid>a051d690-1526-4c7a-917c-bdfed6f59800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AltaShop0</value>
      <webElementGuid>ab21cf5c-57f2-49a9-8994-3d34d3a2be26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/header[@class=&quot;v-sheet theme--dark v-toolbar v-app-bar v-app-bar--fixed deep-purple accent-4&quot;]/div[@class=&quot;v-toolbar__content&quot;]</value>
      <webElementGuid>6849f2d7-0fe9-4722-a7a5-d1b6f239f55f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>809f5e69-5914-4963-993e-6b114b1aad44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-toolbar__content</value>
      <webElementGuid>423b04f7-14a4-4906-bb87-e14fb3190239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AltaShop0</value>
      <webElementGuid>d3e64dbe-871a-4714-98bd-c71523a846c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/header[@class=&quot;v-sheet theme--dark v-toolbar v-app-bar v-app-bar--fixed deep-purple accent-4&quot;]/div[@class=&quot;v-toolbar__content&quot;]</value>
      <webElementGuid>c3011e9a-f4e7-4c6d-b0a1-81d7c877a944</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/header/div</value>
      <webElementGuid>6e6a14e1-2bd4-4bd8-be99-a1ef98003a69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transactions'])[1]/preceding::div[4]</value>
      <webElementGuid>275695bf-ba0b-4369-8e42-c4ba783ff23f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//header/div</value>
      <webElementGuid>5aae9cf3-7050-413a-8f3e-033a8b35e551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'AltaShop0' or . = 'AltaShop0')]</value>
      <webElementGuid>fb56b3b7-e551-4566-a4d3-47504691ab93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order is empty!'])[1]/preceding::div[4]</value>
      <webElementGuid>915bde08-e2d9-4fdc-a2e1-a9291294b269</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
